urls:
  api: 'https://devnet-api.elrond.com'
  swagger:
    - 'https://devnet-microservice.elrond.com'
    - 'https://testnet-microservice.elrond.com'
    - 'https://microservice.elrond.com'
  redis: '127.0.0.1'
features:
  publicApi: true
  privateApi: true
  transactionProcessor: true
security:
  jwtSecret: ''
contracts:
  pingPong: 'erd1qqqqqqqqqqqqqpgqvuhp2tyyld4fdhnzhur8lkr8mxrp72x2gn8qx80urf'