urls:
  api: 'https://api.elrond.com'
  swagger:
    - 'https://microservice.elrond.com'
    - 'https://devnet-microservice.elrond.com'
    - 'https://testnet-microservice.elrond.com'
  redis: '127.0.0.1'
features:
  publicApi: true
  privateApi: true
  transactionProcessor: true
security:
  jwtSecret: ''
contracts:
  pingPong: 'erd1qqqqqqqqqqqqqpgquvt728n40ssd8n2qns9jrlqpwq2jc4rj4cysfuj3ad'