[package]
name = "ping-pong"
version = "0.0.2"
authors = [ "Bruda Claudiu-Marcel <claudiu725@yahoo.com>",]
edition = "2018"
publish = false

[lib]
path = "src/ping_pong.rs"

[dependencies.elrond-wasm]
version = "0.29.3"

[dev-dependencies.elrond-wasm-debug]
version = "0.29.3"
